version: "3"

services:
    influxdb:
        build: ./influxdb
        container_name: ${CONTAINER_PREFIX}_influxdb
        ports:
            - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
        volumes:
            - influxdb_data:/var/lib/influxdb
        restart: always
        env_file:
            - .env
        networks:
            - backend
            - frontend

    telegraf:
        build: ./telegraf
        container_name: ${CONTAINER_PREFIX}_telegraf
        links:
            - influxdb
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
        env_file:
            - .env
        networks: 
            - backend
            
    grafana:
        build: ./grafana
        container_name: ${CONTAINER_PREFIX}_grafana
        ports: 
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        links:
            - influxdb
        volumes:
            - grafana_lib:/var/lib/grafana
            - grafana_log:/var/log/grafana
            - grafana_plugins:/var/lib/grafana/plugins
        restart: always
        env_file:
            - .env
        networks:
            - frontend

networks:
    backend:
    frontend:

volumes:
    influxdb_data:
        name: influxdb_data
    grafana_lib:
        name: grafana_lib
    grafana_log:
        name: grafana_log
    grafana_plugins:
        name: grafana_plugins
